# Generated by Django 4.2.18 on 2025-01-28 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0003_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the user providing the testimonial.', max_length=100, null=True)),
                ('testimonial_text', models.TextField(help_text='The testimonial content.')),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False, help_text='Only approved testimonials are shown.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
